###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  banda:
    name: Banda
    desc: ⚡️ JS library that will make it easy to create complex HTML components in a fast, declarative and reusable way
    type:
      - library
    status: idea
    logo: https://raw.githubusercontent.com/pigeonposse/banda/main/docs/logo.png

###############################################################################
